# descriptive statistik
  meringkas, mengatur, mudah di pahami, tidak membuat kesimpulan
  
# yang diukur 
* central tendency (nilai tengah)
    - average/mean
    - median
    - mode
* spread (sebaran)
    - stdv
    - mean deviasion
    - variant
    - percentil
    - quadratil
    

# Bentuk kurva
* bedasarkan nilai tengah 
    - positif skew
    - simetrical skew
    - negative skew
* berdasarkan sebaran (kurtosis)
    - Leprokurtic
    - Mesokurtic
    - platykurtic
    

# korelasi 
 * no colerasion
 * negatif corelation
 * positif corelation 
    

In [1]:
import math
import statistics
import numpy as np
import scipy.stats
import pandas as pd

x = [8.0, 1,2,1.5,8, 17]
x_with_nan = [8.0, 1,2, math.nan,1.5,8, 17]

print(x)
print(x_with_nan)


/Users/franatagola/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/franatagola/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)
/Users/franatagola/opt/anaconda3/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 192 from C header, got 216 from PyObject
  return f(*args, **kwds)


[8.0, 1, 2, 1.5, 8, 17]
[8.0, 1, 2, nan, 1.5, 8, 17]


In [3]:
y, y_with_nan = np.array(x), np.array(x_with_nan)
z, z_with_nan = pd.Series(x), pd.Series(x_with_nan)

In [4]:
z

0     8.0
1     1.0
2     2.0
3     1.5
4     8.0
5    17.0
dtype: float64

In [5]:
y

array([ 8. ,  1. ,  2. ,  1.5,  8. , 17. ])

In [6]:
z_with_nan

0     8.0
1     1.0
2     2.0
3     NaN
4     1.5
5     8.0
6    17.0
dtype: float64

In [7]:
y_with_nan

array([ 8. ,  1. ,  2. ,  nan,  1.5,  8. , 17. ])

In [10]:
# central tendency
print(z.mean())
print(z_with_nan.mean())
print(np.mean(y_with_nan))




6.25
6.25
nan


In [11]:
#weighted mean
w = [0.7, 0.8,0.1,0.2,0.3, 0.7]


In [20]:
wmean = sum(w[i] * x[i] for i in range(len(x)))/sum(w)
wmean

7.57142857142857

In [23]:
wmeanbp = np.average(y, weights = w)

In [24]:
wmeanbp

7.57142857142857

In [27]:
# harmonic mean seorang bapak jalan kaki 5 km pertama dengan kecepatan 2 km/jam dan 5 km kemudian dengan kecepatan 4km/jam
# n/ sigma(1/n)
# 2/(1/2 + 1/4)
harmonicmean = len(x)/sum(1/i for i in x)
harmonicmean

2.423762376237624

In [29]:
harmonicmean_stat = statistics.harmonic_mean(x)
harmonicmean_stat

2.4237623762376237

In [31]:
harmonicmean_scipy = scipy.stats.hmean(x)
harmonicmean_scipy

2.423762376237624

In [37]:
# geometric mean  
# laptop1 harga 20jt lama pakai 7 tahun
# laptop 2 harga 12jt lama pakai 4 tahun 
# laptop 1 geometrik meannya
geoMEanLaptop1 = math.sqrt(1/20 * 7)
geoMEanLaptop2 = math.sqrt(1/12 * 4)
print(geoMEanLaptop1,geoMEanLaptop2)

0.5916079783099616 0.5773502691896257


In [47]:
# median nilai tegah 
# cara hitung median urutkan dari besar ke kecil, jika n/2 = 0 median index[n/2] jika n/2 != 0 median index[(n + 1)/2] 
medianData = [0.7, 0.8,0.1,0.2,0.3, 0.7, 0.9]
medianData.sort()
medianData

[0.1, 0.2, 0.3, 0.7, 0.7, 0.8, 0.9]

In [48]:
medianstat = statistics.median_high(medianData)
medianstat

0.7

In [49]:
medianstat = statistics.median_low(medianData)
medianstat

0.7

In [58]:
# modus 
modusData=[1,1,1,3,4,5,6,7,8,9,1]
modus = max(((modusData.count(item), item) for item in set(modusData)))[1]
modus


1

In [60]:
modusStat = statistics.mode(modusData)
modusStat

1

In [67]:
# variablility 
variancestate = statistics.variance(modusData)
mean_ = sum(modusData) / len(modusData)
variance = sum((item - mean_)**2 for item in modusData)/ (len(modusData) -1)
print(variance, variancestate)

9.163636363636362 9.163636363636364


In [68]:
stdv = math.sqrt(variance)
stdvState = statistics.stdev(modusData)
print(stdv, stdvState)

3.027149874657078 3.027149874657078


In [70]:
# skewnes
skwnes = scipy.stats.skew(modusData)
skwnes

0.24935156205469858

In [78]:
# percentile
fivepercentile = np.percentile(modusData, 100)
fivepercentile

9.0

In [80]:
# range max val - min val
rangeData = max(modusData) - min(modusData)
rangeData

8

In [81]:
describeData = scipy.stats.describe(modusData)

In [82]:
describeData

DescribeResult(nobs=11, minmax=(1, 9), mean=4.181818181818182, variance=9.163636363636364, skewness=0.24935156205469858, kurtosis=-1.3784722222222225)

In [99]:
x = np.array([0, 1,2,3,4,5,6,7,8,9,])
y = np.random.rand(10)
print(x, y)

[0 1 2 3 4 5 6 7 8 9] [0.01566066 0.16259462 0.3774031  0.34779856 0.87451875 0.24607375
 0.95436186 0.54618988 0.0257153  0.25031765]


In [101]:
covarianxy = np.cov(x, y)
covarianxy

array([[9.16666667, 0.17716314],
       [0.17716314, 0.1048203 ]])

TypeError: 'int' object is not callable

In [104]:
#  2 D data 
twod = np.array([
    [1,1,1],
    [1,2,4],
    [4,8,9],
    [5,6,7]
    
])
twod 


array([[1, 1, 1],
       [1, 2, 4],
       [4, 8, 9],
       [5, 6, 7]])

In [105]:
np.mean(twod)

4.083333333333333

In [106]:
twod.mean()

4.083333333333333

In [108]:
np.median(twod)

4.0

In [111]:
xmed = np.mean(twod, axis=0)
ymed = np.mean(twod, axis=1)

print(xmed, ymed )

[2.75 4.25 5.25] [1.         2.33333333 7.         6.        ]


In [112]:
scipy.stats.gmean(twod)

array([2.11474253, 3.13016916, 3.9842826 ])

In [114]:
scipy.stats.gmean(twod, axis=1)

array([1.        , 2.        , 6.6038545 , 5.94392195])

In [115]:
scipy.stats.describe(twod)

DescribeResult(nobs=4, minmax=(array([1, 1, 1]), array([5, 8, 9])), mean=array([2.75, 4.25, 5.25]), variance=array([ 4.25      , 10.91666667, 12.25      ]), skewness=array([ 0.11531718,  0.13205603, -0.18515606]), kurtosis=array([-1.84775087, -1.71586737, -1.41302235]))

In [117]:
scipy.stats.describe(twod, axis=1 )

DescribeResult(nobs=3, minmax=(array([1, 1, 4, 5]), array([1, 4, 9, 7])), mean=array([1.        , 2.33333333, 7.        , 6.        ]), variance=array([0.        , 2.33333333, 7.        , 1.        ]), skewness=array([ 0.        ,  0.38180177, -0.59517006,  0.        ]), kurtosis=array([-3. , -1.5, -1.5, -1.5]))

In [119]:
row_names =[1,2,3,4]
col_name = ["a","b","c"]

df =pd.DataFrame(twod, index = row_names, columns= col_name)
df

a  b  c
1  1  1  1
2  1  2  4
3  4  8  9
4  5  6  7

In [120]:
df.mean()

a    2.75
b    4.25
c    5.25
dtype: float64

In [121]:
df.var()

a     4.250000
b    10.916667
c    12.250000
dtype: float64

In [122]:
df.mean(axis = 1)

1    1.000000
2    2.333333
3    7.000000
4    6.000000
dtype: float64

In [123]:
df.mean().mean()

4.083333333333333

In [124]:
df.describe()

a         b     c
count  4.000000  4.000000  4.00
mean   2.750000  4.250000  5.25
std    2.061553  3.304038  3.50
min    1.000000  1.000000  1.00
25%    1.000000  1.750000  3.25
50%    2.500000  4.000000  5.50
75%    4.250000  6.500000  7.50
max    5.000000  8.000000  9.00